spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 1 #SpringBoot的接口第一次访问很慢，因为DispatchServlet默认是懒加载的
    pathmatch:
      #解决整合Swagger报错的问题->https://blog.csdn.net/dchua123/article/details/121918921
      matching-strategy: ant_path_matcher
  servlet:
    multipart: #文件上传的大小上限
      max-file-size: 256MB
      max-request-size: 256MB
  datasource:
    username: quanquan
    password: wlqyanyalun008++
  mail:
    username: 836200779@qq.com
    password: alwrojjgukoubdgj
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    port: 465

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #https://www.cnblogs.com/zhaodalei/p/16850870.html
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/dao/**/*.xml

alipay:
  app-id: 2021000121687880
  # PKCS8格式的RSA2私钥
  merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCPq7llZDAvmsIHeO9s02vdZmA66iSxiz5jTrwwGubYHGZ63LockJ/77C+1jGAy3++G90pWJNJjeSj6jAvGBOg8RQNUv+8N7gIOzxWq3lbAUavVueiyTsaJKLjsoRCfB0E+dUmUYQYVYHYRcIz8YKV5OhGrLO/UAeSRO60JmqeJYJCfuFhuqn1Oo9A/X+5rKaqV4yF1V/OTueRPzmOVeAWuf2KgqmXX0/q5BBn6uEAsR5sTQE1y6thSUBbuyf//vj0x5/z62H3l+RbdxNtlA4cXmG0Byie75yZm6NZ6ezOdAMcp/RTM7o+UY+/Dqc2IRgfnQ/Jh0gcK1FrunPIo3W5xAgMBAAECggEAV/yLJhUdjYnxmjHuL2+rd4PjGzGaF0F3i8oEZlGTXnbGLChRsny//cC/1yeJIp8SSk3YMLmMP29MMWTjMPqAX6jESXriJF3G1NruIh7Ych+SZOneIJUt8YIG/qQFUd9XjbC2xzBEUYMpy7RqI4Xs0TlG6NY0alpeaLNrXZ5hTDfsj7s1ZOYJ2vlqRpFJmAgjX+pxVWOR++BqsqKAJo4933zmb3ku2ipMzAjGyLdT09T303S5kKsENF+oDVMkwtl949JKo0rm8DHZIz3X3t678wlKwfbqBY59r1paEpXmQbbBoFX7SyAwYe9tkqXDyrMAW8cdEO9PaPgevXDoYgbAIQKBgQD4Vs77vjVWTOakFdq1UI/d0rAmxAnNz/NXZJvr1nj50MSonYB0Z+HLJrO0JPbShYRlidnf2asFdj6WgFVLj+5ASYTtq25POF38vZ0YnlyetE3/zQibOs1B61FtSHZkp/3ETzs3AsGRCbqUG6cHwypnASs1zVBFROooegjR8KX+ZwKBgQCUGlNp2ntIk2YWed1LNbxfxP+9nWy3Zd8acmJdJ49SMfTb6saN3Pt6sXSo39HhgzEl3m6pkkfNwskeLHVNyMNHEQC91hbkkWIY0UZbXcAYzPv2PhVPF0TWDlfswuIa4xHJm8sHKkmZCU+A5HS5hUgNl9NIv+cK115v9Tf8YVl1ZwKBgQCvSvdHk3eqtxWGdTawDXG/rlxQwMf60vJ9mbLFwdoa3FY0fxiRElK7R1JJsl3XNA/EbI2yCL9DV7fOHEAY2jvefQarjPqMSMlvAZjGK+JM1BDKozuT9umzwhrz/NY1Lq9dxl+R8QwZCLj+mpZIUGa51oVdsNMcUgzHDXz0U92XuQKBgA7g9jBUOr530HHBnHHJ3Dri1658+kcSfO9zPl6NcuCXFDpjw77MzJbu7QFqOvOk8nMTfZqbj4skXoAhh0dhO/0PwDtSHsqnsGs92wuix4G2VjnO0uU3OTsoBb1LdtuspETU2fjGTs6JGOuiB/f7Y9m5vwg3/0YfjOVChXVdcldRAoGBAIsxnt6byV7lGK+QgpUKM3aUA7PymYD6+1T/rNEXsl4CjARgb++fIIWPIudlyYGPLSBufOxe1vnT54ObRwngDjIAiBwB0EY6dHWBrOdyt4yu9W//stsk2GAWfn4An230NCfnSaRto2Kuy4TeTbxSagx5O8h/FTXHHKQmlLbE74iQ
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAA11uJ0JwDUdCeYu4XwhgT4w646E5tKsgGaLSDpYadTT6zMgKBrnF/cW6KMwpqlbIQhEbIZeylTRArmIQc5bSI2aAxVA6+9s/gr6y35mYl2YEhLj0R86mXdIH/DVwVIK+tZ93sOTOtXwrDUZR1LBOMhOCX3RLWfQpCsZL2U5TzRNkqfIWzYmhKFjrggHu74W/jrRoxJO7TiKO+xzTNmrVIerxAuYVsMsGscUSG4Ga0MckUl/bwPPWReeWPfXXJrBAXXbZHanJvGXgx6nyknCXAc/NltPNjwPzX83lgmmLF2ZRRgzFn9fevrEsctNzEIey/Tvp0mGX5rLFAydkua0wIDAQAB
  sign-type: RSA2 #签名方式
  charset: utf-8
  gateway-url: https://openapi.alipaydev.com/gateway.do
  pay-timeout: 15m #支付超时时间

#debug: true

