server:
  ssl:
    key-alias: alias
    key-store-password: VO8Pqyrl
    key-store-type: PKCS12
    key-store: classpath:7998226_quanquancho.com.pfx

spring:
  redis:
    timeout: 300ms #连接超时时间
    host: redis #docker-compose中定义的域名
    password: c6e9a5e5v2ae5va2aw1
  #    port: 6379
#    database: 0 #数据库编号
  datasource:
    url: jdbc:mysql://172.19.37.114:3306/sustech_regency?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

alipay:
  notify-url: https://quanquancho.com:8080/public/payed #必须可以公网访问，支付宝异步回调URL
#  return-url: #必须可以公网访问，支付宝同步回调地址，如果是二维码扫码支付可以不配置

file-root-path: file #容器内的文件绝对路径
