spring:
  redis:
    timeout: 300ms #连接超时时间
  datasource:
    url: jdbc:mysql://quanquancho.com:3306/sustech_regency?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

#    host: localhost
#    port: 6379
#    database: 0 #数据库编号
