spring:
  redis:
    timeout: 300ms #连接超时时间
  datasource:
    url: jdbc:mysql://quanquancho.com:3306/sustech_regency?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
file-root-path: backend/file #相对于项目根目录的路径

#    host: localhost
#    port: 6379
#    database: 0 #数据库编号
