spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 1 #SpringBoot的接口第一次访问很慢，因为DispatchServlet默认是懒加载的
    pathmatch:
      #解决整合Swagger报错的问题->https://blog.csdn.net/dchua123/article/details/121918921
      matching-strategy: ant_path_matcher
  servlet:
    multipart: #文件上传的大小上限
      max-file-size: 256MB
      max-request-size: 256MB
  datasource:
    username: quanquan
    password: wlqyanyalun008++
  mail:
    username: 836200779@qq.com
    password: alwrojjgukoubdgj
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    port: 465

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/dao/**/*.xml

#debug: true

