server:
  ssl:
    key-alias: alias
    key-store-password: VO8Pqyrl
    key-store-type: PKCS12
    key-store: classpath:7998226_quanquancho.com.pfx
file-root-path: file #容器内的文件绝对路径

spring:
  redis:
    timeout: 300ms #连接超时时间
    host: redis #docker-compose中定义的域名
  datasource:
    url: jdbc:mysql://172.19.37.114:3306/sustech_regency?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
#    port: 6379
#    database: 0 #数据库编号

debug: true
