version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: sustech-regency-nginx
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/etc/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
    privileged: true #容器内的root有真正的root权限，否则只是一个普通用户，没有.conf文件权限

  # https://juejin.cn/post/7081931407630532616
  redis:
    image: redis:7.0.5
    container_name: sustech-regency-redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data:/data #挂载数据目录
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    entrypoint: ["redis-server","/etc/redis/redis.conf"]
    privileged: true #容器内的root有真正的root权限，否则只是一个普通用户，没有.conf文件权限

  main:
    image: openjdk:17
    container_name: sustech-regency-main
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./sustech-regency-main-0.0.1-SNAPSHOT.jar:/main.jar
      - ./file:/file
    entrypoint: ["java","-jar","/main.jar","--spring.profiles.active=prod"]
    depends_on:
      - redis
