name: DevOps
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  check-file-changed: #https://www.meziantou.net/executing-github-actions-jobs-or-steps-only-when-specific-files-change.htm
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.check-file-changed.outputs.frontend_changed }}
      backend_changed: ${{ steps.check-file-changed.outputs.backend_changed }}
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
        with: #https://stackoverflow.com/questions/60052236/git-diff-gives-me-a-fatal-bad-revision-head1
          fetch-depth: 0 # '0' indicates all history for all branches and tags
      - name: 执行Shell脚本
        id: check-file-changed
        working-directory: .github/workflows
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        run: |
          sudo chmod +x check-diff.sh
          ./check-diff.sh

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: check-file-changed
    if: needs.check-file-changed.outputs.frontend_changed == 'True'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: 安装Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: 安装依赖
        working-directory: frontend
        run: npm ci
      - name: npm编译打包
        working-directory: frontend
        run: npm run build
      - name: 上传静态文件到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/root/sustech-regency/nginx/html"
          strip_components: 2

  backend-build:
    runs-on: ubuntu-latest
    needs: check-file-changed
    if: needs.check-file-changed.outputs.backend_changed == 'True'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 迁出代码
        uses: actions/checkout@v3
      - name: 安装JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven打包
        working-directory: backend
        run: |
          mvn clean
          mvn package -Dmaven.test.skip=true
      - name: 上传Jar包到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "backend/sustech-regency-main/target/*.jar"
          target: "/root/sustech-regency"
          strip_components: 3
  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 重启Jar包容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/sustech-regency
            docker-compose restart main
