name: DevOps
on:
  push:
    branches:
      - master

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: 安装Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: 安装依赖
        run: |
          cd frontend
          npm i
      - name: 编译打包
        run: |
          cd frontend
          npm run build
      - name: 复制文件到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/root/sustech-regency/nginx/html"

#  backend-build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#          cache: maven
#      - name: Package by Maven
#        run: mvn package --file backend/main/pom.xml