name: DevOps
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  check-file-changed: #https://www.meziantou.net/executing-github-actions-jobs-or-steps-only-when-specific-files-change.htm
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.check-file-changed.outputs.frontend_changed }}
      backend_changed: ${{ steps.check-file-changed.outputs.backend_changed }}
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - name: 执行Shell脚本
        id: check-file-changed
        shell: pwsh
        run: |
          # 1.分割commits的Json字符串，获取commits数量:https://www.yiibai.com/bash/bash-split-string.html
          $commitsStr='${{ toJSON(github.event.commits) }}'
          echo $commitsStr
          IFS='{ "author": { "email":' #定义分割符
          read -ra splits <<<"$commitsStr" #生成splits数组
          echo $splits
          $commitsNumber=${#splits[@]}-1

          # 2.Diff HEAD with the commit number
          echo $commitsNumber
          $diff = git diff --name-only HEAD~$commitsNumber
          echo $commitsNumber

          # 3.Check if a file under /frontend or /backend has changed (added, modified, deleted)
          $FrontendDiff = $diff | Where-Object { $_ -match '^frontend/' -or $_ -match '^.github/workflows/' }
          $BackendDiff = $diff | Where-Object { $_ -match '^backend/' -or $_ -match '^.github/workflows/' }
          $FrontendHasDiff = $FrontendDiff.Length -gt 0
          $BackendHasDiff = $BackendDiff.Length -gt 0

          # 4.Set the output named "frontend_changed" and "backend_changed"
          Write-Host "::set-output name=frontend_changed::$FrontendHasDiff"
          Write-Host "::set-output name=backend_changed::$BackendHasDiff"

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: check-file-changed
    if: needs.check-file-changed.outputs.frontend_changed == 'True'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: 安装Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: 安装依赖
        run: |
          cd frontend
          npm ci
      - name: npm编译打包
        run: |
          cd frontend
          npm run build
      - name: 上传静态文件到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/root/sustech-regency/nginx/html"
          strip_components: 2

  backend-build:
    runs-on: ubuntu-latest
    needs: check-file-changed
    if: needs.check-file-changed.outputs.backend_changed == 'True'
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 迁出代码
        uses: actions/checkout@v3
      - name: 安装JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven打包
        run: |
          cd backend
          mvn clean
          mvn package -Dmaven.test.skip=true
      - name: 上传Jar包到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "backend/sustech-regency-main/target/*.jar"
          target: "/root/sustech-regency"
          strip_components: 3
  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build
    env:
      TZ: Asia/Shanghai
    steps:
      - name: 重启Jar包容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/sustech-regency
            docker-compose restart main
